# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_auto_20180501_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
    ]
