# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180326_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_items',
            name='type_item',
        ),
        migrations.AddField(
            model_name='cart_items',
            name='year_in_school',
            field=models.CharField(choices=[('PEN', 'pen'), ('PENCIL', 'pencil'), ('PAPER', 'paper')], default='PEN', max_length=2),
        ),
    ]
