# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180326_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart_items',
            old_name='year_in_school',
            new_name='item_type',
        ),
    ]
