# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180326_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_items',
            name='item_type',
            field=models.CharField(choices=[('PEN', 'pen'), ('PENCIL', 'pencil'), ('PAPER', 'paper')], default='PEN', max_length=6),
        ),
    ]
