# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20180326_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupon',
            name='cart_items',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='products.Cart_items'),
        ),
    ]
