# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180326_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='cart_items',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.Cart_items'),
        ),
    ]
