# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20180326_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_items',
            name='item_class',
            field=models.CharField(choices=[('COUPON', 'coupon'), ('PRODUCT', 'product')], default='PRODUCT', max_length=7),
        ),
    ]
